### ISSUE TITLE
Largest Element in Array

### ISSUE THREAD

**Issue by SUGAM-ARORA** [SUGAM-ARORA/uknow#1]
Given an array A[] of size n. The task is to find the largest element in it.
 

Example 1:

Input:
n = 5
A[] = {1, 8, 7, 56, 90}
Output:
90
Explanation:
The largest element of given array is 90.

**Comment by Ayush0316** [comment]
I would like to help you in this.

**Comment by SUGAM-ARORA** [comment]
sure
happy learning

**Comment by SUGAM-ARORA** [comment]
Done
